# Required vars
######################################

gardener_kubeconfig_path: "{{ lookup('env', 'GARDENER_KUBECONFIG_PATH') }}" # The path to your KUBECONFIG use a local file to use --check and --diff or use {{ lookup('env', 'GARDENER_KUBECONFIG_PATH') }} to run through the pipeline

gardener_kubeconfig_raw: "{{ lookup('env', 'GARDENER_KUBECONFIG_RAW') }}" # The raw content of a KUBECONFIG

gardener_namespace: garden-test # Namespace where to deploy the Shoot.

gardener_k8s_version: 1.18.5 # Version of Kubernetes to deploy.

gardener_shoot_name: test

gardener_shoot_purpose: development # The purpose of the Gardener Shoot cluster (evaluation|development|testing|production).

gardener_resource_name: gardener-test

# Gardener shoot vars
##########################################
gardener_shoot_allow_delete: # This enables/disables the `confirmation.gardener.cloud/deletion` annotation

gardener_shoot_azs: # A list of availability zones in the region
  - us-east-1a 
  - us-east-1b
  - us-east-1c 

gardener_shoot_auditpolicy_name: test-audit-policy

gardener_shoot_workers:
  - name: gardener-node
    auto_scaler_min: 1
    auto_scaler_max: 2
    machine_type: "m5.large"
    max_surge: 1
    max_unavailable: 0
    volume_type: gp2
    volume_size: 50Gi
    annotations: {}
    labels: {}
    zones: 
      - us-east-1a
      - us-east-1b
      - us-east-1c
    taints: []
  - name: gardener-node1
    auto_scaler_min: 1
    auto_scaler_max: 2
    machine_type: "m5.large"
    max_surge: 1
    max_unavailable: 0
    volume_type: gp2
    volume_size: 50Gi
    annotations: {}
    labels: {}
    zones: 
      - us-east-1b
    taints: []


# OIDC config
######################################
gardener_shoot_oidc_config:
  clientid: 
  groupsClaim: groups
  issuerURL: 
  usernameClaim: email

# VPC vars
######################################
gardener_shoot_vpc_id: # The ID of an exiting VPC. Gardener will create one if left empty (default).

gardener_shoot_vpc_cidr: "10.250.0.0/16" # The CIDR range for the nodes.

gardener_shoot_vpc_cidr_mask:  # The size of the CIDR mask to use for nodes.

gardener_shoot_vpc_nodes_cidr:  # The CIDR range for the nodes.

gardener_shoot_nodeCIDRMaskSize: 16 

gardener_shoot_vpc_pods_cidr: "100.96.0.0/11" # The CIDR range for a new VPC.

gardener_shoot_vpc_services_cidr: "100.64.0.0/13" # The CIDR range for a new VPC.

# Extra variables to delete deployed ressource
######################################
gardener_secret_state: present # Define if the gardener secret should be "present" or "absent"
gardener_auditpolicy_state: present # Define if the gardener  auditpolicy should be "present" or "absent"
gardener_shoot_state: present # Define if the gardener shoot should be "present" or "absent"

