---
apiVersion: v1
kind: Secret
metadata:
  finalizers:
    - gardener.cloud/gardener
  name: {{ gardener_secret_name }}
  namespace: {{ gardener_namespace }}
data:
  accessKeyID: {{ base64_access_key }}
  secretAccessKey: {{ base64_secret_key }}
type: Opaque

---

apiVersion: core.gardener.cloud/v1alpha1
kind: SecretBinding
metadata:
  labels:
    cloudprofile.garden.sapcloud.io/name: {{ gardener_cloudprofile }}
  name: {{ gardener_secret_name }}
  namespace: {{ gardener_namespace }}
secretRef:
  name: {{ gardener_secret_name }}
  namespace: {{ gardener_namespace }}
