---
- name: TEST
  shell: echo test2

- debug:
    msg: TEST2
    
#  - name: Deploy gardener
#    block:
#     # 1. Ensure that theres a kubeconfig and it point to a file path so we can authenticate (if not create a tmp file with the content)
#     - name: Copy kubeconfig data to "{{ gardener_kubeconfig_path }}"
#       copy:
#         content: "{{ gardener_kubeconfig_raw }}"
#         dest: "{{ gardener_kubeconfig_path }}"
#       when: gardener_kubeconfig_raw is defined
#       no_log: True
#       changed_when: False

#     # 2. Deploy k8s resource using templates
#     - name:  Create gardener secret by using gardener_secret.yaml template
#       vars:
#         base64_access_key: "{{ iam_created_users.results[0].user_meta.access_keys[0].access_key_id | b64encode }}"
#         base64_secret_key: "{{ iam_created_users.results[0].user_meta.access_keys[0].secret_access_key | b64encode }}"
#       k8s:
#         state: "{{ gardener_secret_state }}"
#         kubeconfig: "{{ gardener_kubeconfig_path | from_yaml }}"
#         definition: "{{ lookup('template', 'files/k8s_resources/gardener_secret.yaml') }}"
#       register: secret_status_result
#       when: (iam_created_users) and (iam_created_users.results[0].user_meta.access_keys[0].secret_access_key is defined)
#       no_log: True

#     - include_vars: roles/gardener/defaults/audit_policy.yaml
#       when: gardener_shoot_audit_subaccount_id is defined

#     - name: Create gardener auditpolicy by using gardener_auditpolicy.yaml template
#       k8s:
#         state: "{{ gardener_auditpolicy_state }}"
#         kubeconfig: "{{ gardener_kubeconfig_path | from_yaml }}"
#         definition: "{{ lookup('template', 'files/k8s_resources/gardener_auditpolicy.yaml') }}"
#       when: gardener_shoot_audit_subaccount_id is defined

#     - name:  Create gardener shoot by using gardener_shoot.yaml template
#       k8s:
#         state: "{{ gardener_shoot_state }}"
#         kubeconfig: "{{ gardener_kubeconfig_path | from_yaml }}"
#         definition: "{{ lookup('template', 'files/k8s_resources/gardener_shoot.yaml') }}"

#    always:
#     # 3. Cleanup 
#     - name: Delete the kubeconfig stored in the host"
#       file:
#         path: "{{ gardener_kubeconfig_path }}"
#         state: absent
#       no_log: True
#       changed_when: False
