name: deploy_gardener_workflow

on:
  push:
    branches: [ ansible-actions ]
    paths:
      - '.github/workflows/deploy_gardener.yml'
      - '.actions/gardener/actions/deploy_gardener.yml'
      - '.actions/gardener/actions/Dockerfile'
  pull_request:
    branches: [ master, ansible-actions ]

jobs:
  deploy_gardener_job:
    runs-on: ubuntu-16.04
    name: Run deploy_gardener.yml Ansible playbook to deploy gardener Stage Infra
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - run: ls $GITHUB_WORKSPACE/

      - run: cp -r $GITHUB_WORKSPACE/.actions/gardener/ansible-playbook $GITHUB_WORKSPACE/.actions/gardener/actions/ansible-playbook
     
      - name: Ansible Playbook syntax-check
        uses: ansible/ansible-lint-action@master
        with:
          targets: |
            ./.actions/gardener/ansible-playbook/cla_assistant_stage-us-east-1.yml
          args: "-x 201,502,208,106,301,305"

      - name: Execute Playbook Action Step
        uses: ./.actions/gardener/actions # Uses an action in the actions directory
        id: Execution
        with:
          playbookName: "./.actions/gardener/ansible-playbook/cla_assistant_stage-us-east-1.yml"
          inventoryFile: "./.actions/gardener/ansible-playbook/local_inventory"
          extraVars: "-e 'ansible_python_interpreter=/usr/bin/python3'"
          rolesPath: "./.actions/gardener/ansible-playbook/roles"
          verbosity: "-vvv"
        env:
          ANSIBLE_STDOUT_CALLBACK: debug
          ANSIBLE_FORCE_COLOR: true
          GARDENER_KUBECONFIG_PATH: ${{ secrets.GARDENER_KUBECONFIG_PATH }}
          GARDENER_KUBECONFIG_RAW: ${{ secrets.GARDENER_KUBECONFIG_RAW }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SETUPTOOLS_USE_DISTUTILS: stdlib
